"""Remove username field from User Model

Revision ID: 2d64f603518b
Revises: 8fc2aafbfaf1
Create Date: 2024-11-29 21:54:13.001231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d64f603518b'
down_revision = '8fc2aafbfaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
