"""Add document column to professionals table

Revision ID: 9f391fcd475e
Revises: 2d64f603518b
Create Date: 2024-11-29 22:42:58.950770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f391fcd475e'
down_revision = '2d64f603518b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=False))
        batch_op.alter_column('experience',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('pincode')
        batch_op.drop_column('address')
        batch_op.drop_column('document')

    # ### end Alembic commands ###
