"""Add status field to professional model

Revision ID: b57321299807
Revises: 9f391fcd475e
Create Date: 2024-11-30 10:24:15.940142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57321299807'
down_revision = '9f391fcd475e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
